name: (( config_from_cf.cf_deployment_name "-diego-perf" ))
director_uuid: (( config_from_cf.cf_director_uuid ))

releases:
  - name: diego-perf-release
    version: latest
  - name: cf
    version: latest

compilation:
  workers: 6
  network: perf
  reuse_compilation_vms: true
  cloud_properties: (( iaas_settings.compilation_cloud_properties ))

update:
  canaries: 1
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000
  max_in_flight: 1
  serial: false

networks:
  - name: perf
    type: manual
    subnets: (( iaas_settings.subnet_configs.perf.subnets ))

resource_pools:
  - name: perf
    network: perf
    stemcell: (( iaas_settings.stemcell ))
    cloud_properties: (( iaas_settings.resource_pool_cloud_properties.cedar.cloud_properties ))

jobs:
  - name: cedar
    templates:
      - name: arborist
        release: diego-perf-release
      - name: cedar
        release: diego-perf-release
      - name: fezzik
        release: diego-perf-release
    instances: (( instance_count_overrides.cedar.instances || 1 ))
    persistent_disk: 4096
    resource_pool: perf
    networks:
      - name: perf
  - name: post-process
    templates:
    - name: post-process
      release: diego-perf-release
    instances: 1
    lifecycle: errand
    networks:
      - name: perf
    resource_pool: perf

properties:
  cedar:
    api: (( config_from_cf.cc.api_uri ))
    domain: (( config_from_cf.first_app_domain ))
    admin_user: (( property_overrides.cc_admin_user || "" )) # unfortunate hack because we can't get it from cf manifest
    admin_password: (( property_overrides.cc_admin_password || "" ))  # unfortunate hack because we can't get it from cf manifest
    org: (( property_overrides.org ))
    num_batches: (( property_overrides.cedar.num_batches || nil ))
    max_in_flight: (( property_overrides.cedar.max_in_flight || nil ))
    tolerance:  (( property_overrides.cedar.tolerance || nil ))
    timeout:  (( property_overrides.cedar.timeout || nil ))
  arborist:
    duration:  (( property_overrides.arborist.duration || nil ))
    request_interval:  (( property_overrides.arborist.request_interval || nil ))

  fezzik:
    bbs:
      api_location: (( "bbs.service.cf.internal:8889" ))
      ca_cert: (( config_from_diego.bbs.ca_cert ))
      client_cert: (( config_from_diego.bbs.client_cert ))
      client_key: (( config_from_diego.bbs.client_key ))
      require_ssl: (( config_from_diego.bbs.require_ssl || nil ))
  performance_tests:
    num_cells: (( property_overrides.num_cells || nil ))
  post-process:
    gcp:
      username: (( property_overrides.post-process.gcp.username || nil ))
      password: (( property_overrides.post-process.gcp.password || nil ))
      target: (( property_overrides.post-process.gcp.target || nil ))
    influxdb_url: (( property_overrides.post-process.influxdb_url || nil ))

# The keys below should not be included in the final stub
config_from_cf: (( merge ))
config_from_diego: (( merge ))
property_overrides: (( merge ))
iaas_settings: (( merge ))
instance_count_overrides: (( merge || nil ))
