#!/bin/bash

set -e

manifest_generation=$(dirname $0)/../manifest-generation

usage() {
  >&2 cat <<EOF
SYNOPSIS:
    Generate a manifest for a Diego Perf deployment to accompany an existing CF/Diego deployment.

USAGE:
    $0 <MANDATORY ARGUMENTS> [OPTIONAL ARGUMENTS]

MANDATORY ARGUMENTS:
    -c <cf-path>        Path to CF manifest file.
    -d <diego-path>     Path to Diego manifest file.
    -i <iaas-path>      Path to IaaS-settings stub file.
    -p <property-path>  Path to property-overrides stub file.

OPTIONAL ARGUMENTS:
    -n <count-path>     Path to instance-count-overrides stub file.
    -l                  Use the softlayer-specific YAML template.

EXAMPLE:
    $0 \\
      -c ../cf-release/bosh-lite/deployments/cf.yml \\
      -d ../diego-release/bosh-lite/deployments/diego.yml \\
      -i manifest-generation/bosh-lite-stubs/iaas-settings.yml \\
      -p manifest-generation/bosh-lite-stubs/property-overrides.yml \\
      -n manifest-generation/bosh-lite-stubs/instance-count-overrides.yml
EOF
  exit 1
}

base_releases="${manifest_generation}/base-releases.yml"
instance_counts=""

while getopts "c:i:p:n:d:l" opt; do
  case $opt in
    c)
      cf_deployment_manifest=$OPTARG
      ;;
    d)
      diego_deployment_manifest=$OPTARG
      ;;
    i)
      iaas_settings=$OPTARG
      ;;
    p)
      property_overrides=$OPTARG
      ;;
    n)
      instance_counts=$OPTARG
      ;;
    l)
      use_softlayer=1
      ;;
    *)
      echo "Unknown arguments"
      usage
      ;;
  esac
done

if [ -z ${cf_deployment_manifest} ]; then
  >&2 echo "ERROR: CF manifest file is missing"
  argument_error=true
else
  if [ ! -f "${cf_deployment_manifest}" ]; then
    >&2 echo "ERROR: CF manifest '${cf_deployment_manifest}' is not a regular file"
    argument_error=true
  fi
fi

if [ -z ${diego_deployment_manifest} ]; then
  >&2 echo "ERROR: Diego manifest file is missing"
  argument_error=true
else
  if [ ! -f "${diego_deployment_manifest}" ]; then
    >&2 echo "ERROR: CF manifest '${diego_deployment_manifest}' is not a regular file"
    argument_error=true
  fi
fi

if [ -z ${iaas_settings} ]; then
  >&2 echo "ERROR: IaaS-settings stub file is missing"
  argument_error=true
else
  if [ ! -f "${iaas_settings}" ]; then
    >&2 echo "ERROR: IaaS Setting stub '${iaas_settings}' is not a regular file"
    argument_error=true
  fi
fi

if [ -z ${property_overrides} ]; then
  >&2 echo "ERROR: Property-overrides stub file is missing"
  argument_error=true

else
  if [ ! -f "${property_overrides}" ]; then
    >&2 echo "ERROR: Property-overrides stub '${property_overrides}' is not a regular file"
    argument_error=true
  fi
fi

if [[ ! -z "${instance_counts}" && ! -f "${instance_counts}" ]]; then
  >&2 echo "ERROR: Instance-count-overrides stub '${instance_counts}' is not a regular file"
  argument_error=true
fi

if [ ! -z $argument_error ]; then
  echo
  usage
fi

if [[ ${use_softlayer} ]]; then
  template_file=${manifest_generation}/perf-softlayer.yml
else
  template_file=${manifest_generation}/perf.yml
fi

tmpdir=$(mktemp -d /tmp/diego-manifest.XXXXX)

spiff merge \
  ${manifest_generation}/config-from-cf.yml \
  ${manifest_generation}/config-from-cf-internal.yml \
  ${cf_deployment_manifest} \
  > ${tmpdir}/config-from-cf.yml

spiff merge \
  ${manifest_generation}/config-from-diego.yml \
  ${manifest_generation}/config-from-diego-internal.yml \
  ${diego_deployment_manifest} \
  > ${tmpdir}/config-from-diego.yml

spiff merge \
  ${template_file} \
  ${property_overrides} \
  ${instance_counts} \
  ${iaas_settings} \
  ${tmpdir}/config-from-cf.yml \
  ${tmpdir}/config-from-diego.yml \
  > ${tmpdir}/perf.yml

spiff merge \
  ${manifest_generation}/misc-templates/bosh.yml \
  ${tmpdir}/perf.yml
