#!/bin/bash

set -e

manifest_generation=$(dirname $0)/../manifest-generation

function usage() {
  >&2 echo "    Usage:
    $0 /path/to/stub/director-uuid.yml \\
       /path/to/stub/property-overrides.yml \\
       /path/to/stub/instance-count-overrides.yml \\
       /path/to/stub/iaas-settings.yml \\
       /path/to/deployment-manifests

    Ex:
    $0 ~/deployments/bosh-lite/director.yml \\
       manifest-generation/bosh-lite-stubs/property-overrides.yml \\
       manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \\
       manifest-generation/bosh-lite-stubs/iaas-settings.yml \\
       ~/deployments/bosh-lite
"
  exit 1
}

director_uuid=$1
properties=$2
instance_counts=$3
iaas_settings=$4
deployments=$5

if [ -z "${deployments}" ]; then
  >&2 echo "Not enough arguments"
  usage
fi

if [ ! -z "$6" ]; then
  >&2 echo "Too many arguments"
  usage
fi

if [ ! -f "${director_uuid}" ]; then
  >&2 echo "Director UUID stub '${director_uuid}' is not a regular file"
  usage
fi

if [ ! -f "${properties}" ]; then
  >&2 echo "Property Overrides stub '${properties}' is not a regular file"
  usage
fi

if [ ! -f "${instance_counts}" ]; then
  >&2 echo "Instance Count Overrides stub '${instance_counts}' is not a regular file"
  usage
fi

if [ ! -f "${iaas_settings}" ]; then
  >&2 echo "IaaS Setting stub '${iaas_settings}' is not a regular file"
  usage
fi

if [ ! -d "${deployments}" ]; then
  >&2 echo "Deployments directory '${deployments}' is not a directory"
  usage
fi

tmpdir=$(mktemp -d /tmp/diego-manifest.XXXXX)

spiff merge \
  ${manifest_generation}/config-from-cf.yml \
  ${manifest_generation}/config-from-cf-internal.yml \
  ${deployments}/cf.yml \
  > ${tmpdir}/config-from-cf.yml

spiff merge \
  ${manifest_generation}/config-from-diego.yml \
  ${manifest_generation}/config-from-diego-internal.yml \
  ${deployments}/diego.yml \
  > ${tmpdir}/config-from-diego.yml

spiff merge \
  ${manifest_generation}/perf.yml \
  ${properties} \
  ${instance_counts} \
  ${iaas_settings} \
  ${tmpdir}/config-from-cf.yml \
  ${tmpdir}/config-from-diego.yml \
  > ${tmpdir}/perf.yml

spiff merge \
  ${manifest_generation}/misc-templates/bosh.yml \
  ${director_uuid} \
  ${tmpdir}/perf.yml
