#!/bin/bash
 
set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list -app code.cloudfoundry.org/diego-stress-tests/...
  gosub list -test code.cloudfoundry.org/fezzik/...
  gosub list -app github.com/onsi/ginkgo/ginkgo/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync

